server:
  port: 8080
name: Jack
age: 18
content: "name: ${name}, age: ${age}"
person:
  name: haha
  age: 22
hello:
  msg: hi,hello world! I'm default.
spring:
  profiles:
    active:
info:
  head: head
  body: body
management:
  endpoints:
    web:
      exposure:
        #加载所有的端点，默认只加载了info、health
        include: '*'
  endpoint:
    health:
      show-details: always
    #可以关闭指定的端点
    shutdown:
      enabled: false